#! /bin/bash

# Version 25.11.14
# Date: 15 NOV 25

LOGFILE="${HOME}/RPIKiosk.log"
GITPATH="${HOME}/RPIKiosk"
BRANCH="CHS"

ALLOW_SELF_UPDATE=false

FTCLIVE_PORTS="80,8080,18080,28080,38080,48080,58080,4567"
NETWORK_DEVICE=eth0

# export macAddr ipAddr ipMask gatewayAddr hostname server_addr KIOSK_URL

macAddr=""
ipAddr=""
ipMask=""
gatewayAddr=""
hostname=""
server_addr=""
KIOSKURL=""

# ----- Functions -------------------------------------------------------------

emit() {
    # status=$?

    # msg="${*}"
    # dt=$(date)
    # printf '%s %s\n' "${dt}" "${msg}" 1>&2
    printf '%s %s\n' "$(date)" "${*}" >> ${LOGFILE}
    # echo "${*}" >> ${LOGFILE}

    # return $status
}

emit_cmd() {
    cmd=${*}

    ${cmd} 2>&1 | while IFS= read -r line; do
        emit "${line}"
    done
}

report_error_and_exit() {
    message="$*"
    emit ${message}
    cat ${HOME}/RPIKiosk/error.html | sed "s/MESSAGE/${message}/g" > ${HOME}/error.html
    [[ -n "${DISPLAY}"  ]] && chromium-browser --disable-infobars --kiosk "file://${HOME}/error.html"
    exit 1
}

init_logfile() {
    if ! [[ -f "$LOGFILE"  ]] ; then
        sudo touch "$LOGFILE"
        sudo chown $USER:$USER "$LOGFILE"
        sudo chmod 666 "$LOGFILE"
    fi

    emit ===== init_logfile
}

/usr/bin/env | sort > ${HOME}/env.log

disable_screen_saver() {
    emit ===== disable_screen_saver

    if [[ -n "$DISPLAY"  ]] ; then
        emit "DEBUG Disabling screen saver"
        #Disable any form of screen saver / screen blanking / power management
        emit_cmd xset s off
        emit_cmd xset s noblank
        emit_cmd xset -dpms

        #Allow quitting the X server which CTRL-ALT-BACKSPACE
        emit_cmd setxkbmap -option terminate:ctrl_alt_bksp
    else
        emit "DEBUG Skipping screen saver settings"
    fi
}

enable_chromium_kiosk() {
    emit ===== enable_chromium_kiosk
    # Start Chromium in kiosk mode
    CC=${HOME}/.config/chromium/
    cat ${CC}/'Local State' | jq '.user_experience_metrics.stability.exited_cleanly = false' > ${CC}/tmp_localState && mv ${CC}/tmp_localState ${CC}/'Local State'

    rm -f ${CC}/Default/Preferences
}

wait_for_active_interface() {
    emit ===== wait_for_active_interface

    local found=false

    # Wait for etho0 or wlan0 to go to upstate for ~50 seconds
    for i in {1..25} ; do
        if [ "$(cat /sys/class/net/eth0/operstate)" = "up" ] ; then
                # If eth0 goes up
                NETWORK_DEVICE=eth0
                found=true
                break
        # elif  [ "$(cat /sys/class/net/wlan0/operstate)" = "up" ] ; then
        #         # If wlan0 goes up
        #         NETWORK_DEVICE=wlan0
        #         found=true
        #         break
        fi

        # Otherwise sleep
        emit "Waiting Adapter Attempt $i"
        sleep 2
    done

    $found || report_error_and_exit "ERROR 1: System failed to have eth0 or wlan0 go to up state."
}

wait_for_ip_address() {
    emit ===== wait_for_ip_address

    # Wait to receive an IP address for ~50 seconds
    for i in {1..25} ; do
        if ip -f inet -o address | egrep $NETWORK_DEVICE > /dev/null ; then
            macAddr=$(ip -f link -o  address | egrep ' UP .*link/ether' | sed 's;^.*link/ether \([^ ]*\).*$;\1;' | cut -d: -f4-)
            ipMask=$(ip -f inet -o address | egrep eth0 | tr -s ' ' | cut -d' ' -f4)
            ipAddr=$(cut -d'/' -f1 <<< ${ipMask})
            gatewayAddr=$(ip route | grep default | cut -d' ' -f3)
            hostname="kiosk-$(tr -d ':' <<< ${macAddr})"
            break   # If we have an IP address break
        fi

        # Otherwise sleep
        emit "[Waiting IP] Attempt $i"
        sleep 2
    done

    [ -z "${macAddr}" ] && report_error_and_exit "ERROR 2: Failed to receive IP address."

    emit "DEBUG macAddr = ${macAddr}"
    emit "DEBUG ipMask = ${ipMask}"
    emit "DEBUG ipAddr = ${ipAddr}"
    emit "DEBUG gatewayAddr = ${gatewayAddr}"
    emit "DEBUG hostname = ${hostname}"
}

check_for_internet() {
    emit ===== check_for_internet

    # Check if we can access out gateway address on port 80
    if nc -z -w3 $gatewayAddr 80 ; then
        # We have a gateway address and were able to connect to it.
        emit "Able to connect to gateway, proceeding!"
    else
        report_error_and_exit "ERROR 3: Failed to receive IP address. Unable to connect to gateway!"
    fi
}

self_update() {
    emit ===== Running self_update

    cd "$GITPATH"
    git branch -u "origin/$BRANCH"
    git fetch

    if [[ $(git status --branch --porcelain --untracked-files=no | wc -l) -gt 0 ]]; then
        emit "Found a new version of me, updating myself..."

        #Perform a git hard reset to ignore any local changes
        git reset --hard
        git pull --force

        #Overwrite error.html in case there was an update
        sudo rm -f ${HOME}/error.html
        sudo cp -rf error.html ${HOME}/error.html

        #Overwrite autostart in case there was an update
        sudo dos2unix ${HOME}/RPIKiosk/autostart
        sudo rm -f /etc/xdg/openbox/autostart
        sudo ln -sf ${HOME}/RPIKiosk/autostart /etc/xdg/openbox/autostart

        emit "Rebooting"
        sudo reboot #Reboot because we can not exec autostart 
    else
        emit "No git changes, already the latest version."
    fi
}

check_for_updatability() {
    emit ===== check_for_updatability

    if $ALLOW_SELF_UPDATE ; then 
        # If we can reach github on port 80
        if nc -z -w3 github.com 80 ; then
            #run the Self Update
            self_update
        else
            emit "ERROR 3: Unable to access github.com. Not autoupdating!"
        fi
    else
        emit "DEBUG Skipping self update ($ALLOW_SELF_UPDATE)"
    fi
}

test_scoring_system() {
    target_ip=$1
    target_port=$2

    if fgrep ':' <<< $target_ip ; then
        target_port=$(cut -d':' -f2 <<< $target_ip)
        target_ip=$(cut -d':' -f1 <<< $target_ip)
    fi

    status_code=$(curl --silent --output /dev/null --write-out "%{http_code}" "http://${target_ip}:${target_port}/whoami/")
    if [ "$status_code" -eq 200 ] ; then
        if [ "$target_port" -eq 80 ] ; then
            server_addr="${target_ip}"
        else
            server_addr="${target_ip}:${target_port}"
        fi
    else
        return 1
    fi
}

search_for_scoring_system() {
    emit ===== search_for_scoring_system
    NETWORK=$(ipcalc -n "${ipMask}" | awk '/Network/ { print $2 }')

    filter="Nmap|^${gatewayAddr}\$"
    targets=$(nmap -n -T4 -p "${FTCLIVE_PORTS}" --open "${NETWORK}" -oG - | awk '/open/{print $2}' | egrep -v $"$filter")

    emit "DEBUG Checking ${targets} for scoring system"
    for target_ip in $targets; do
        tr ',' '\n' <<< ${FTCLIVE_PORTS} | while read port ; do
            if test_scoring_system ${target_ip} ${port} ; then
                emit "Located scoring system at ${target_ip} ${port} => ${server_addr} [$?]"
                echo $server_addr
                return 0
            fi
        done
    done
}

locate_scoring_system() {
    emit ===== locate_scoring_system

    if [ -n "$FTCEVENTSERVER_IP" ] ; then
        if ! test_scoring_system $FTCEVENTSERVER_IP ; then
            emit "DEBUG FTCEVENTSERVER_IP not valid, searching for server."
            server_addr=$(search_for_scoring_system)
            emit "server_addr = [$server_addr]"
        fi
    else
        emit "DEBUG FTCEVENTSERVER_IP not set, searching for server."
        server_addr=$(search_for_scoring_system)
        emit "server_addr = [$server_addr]"
    fi

    [ -z "${server_addr}" ] && report_error_and_exit "ERROR 5: FTC Server ($server_addr) is NOT online! Please check if the IP is correct or if the server is online."
}

find_event_codes() {
    emit ===== find_event_codes

    if [ -z "$FTCEVENTSERVER_EVENTCODE" ] ; then
        FTCEVENTSERVER_EVENTS=$(curl -s -L -X GET http://${server_addr}/api/v1/events)
        numFTCEVENTSERVER_EVENTS=$(echo $FTCEVENTSERVER_EVENTS | jq -r ".eventCodes" | jq length)

        if [ $numFTCEVENTSERVER_EVENTS -eq 1 ] ; then
            FTCEVENTSERVER_EVENTCODE=$(echo $FTCEVENTSERVER_EVENTS | jq -r ".eventCodes[]")
            emit "Found event code $FTCEVENTSERVER_EVENTCODE"
        elif [ $numFTCEVENTSERVER_EVENTS -eq 3 ] ; then 
            # We are most likely a dual division event so process it!
            emit "Found 3 Events. Checking if this is a dual division event."

            FTCEVENTSERVER_DIVISION0_EVENTCODE=$(echo $FTCEVENTSERVER_EVENTS | jq -r '.eventCodes[] | select( . |  contains("_0"))')
            emit "First event code is: $FTCEVENTSERVER_DIVISION0_EVENTCODE"

            FTCEVENTSERVER_DIVISION1_EVENTCODE=$(echo $FTCEVENTSERVER_EVENTS | jq -r '.eventCodes[] | select( . |  contains("_1"))')
            FTCEVENTSERVER_DIVISION2_EVENTCODE=$(echo $FTCEVENTSERVER_EVENTS | jq -r '.eventCodes[] | select( . |  contains("_2"))')
            emit "System is a dual division event. Found event codes D1# $FTCEVENTSERVER_DIVISION1_EVENTCODE and D2# $FTCEVENTSERVER_DIVISION2_EVENTCODE"
        else 
            KIOSKURL="http://${server_addr}/"
            emit "Failed to find event code!"
        fi
    else
        emit "FTCEVENTSERVER_EVENTCODE is already set to: ${FTCEVENTSERVER_EVENTCODE}"
    fi
}

read_gpio_switches() {
    emit ===== read_gpio_switches

    # Pin Setup
    # https://learn.sparkfun.com/tutorials/raspberry-gpio/gpio-pinout
    #
    # MODE Pins
    # PIN 32/12 - FIELD Display
    # PIN 36/16 - PIT DISPLAY
    # PIN 38/20 - INSPECTIONS DISPLAY
    # PIN 40/21 - AUDIENCE DISPLAY
    #
    # FIELD Pins
    # PIN 21/6 = FIELD 1
    # PIN 33/13 = FIELD 2
    # PIN 35/19 = FIELD 3
    # PIN 37/26 = FIELD 4
    #

    raspi-gpio set 12 ip pd
    raspi-gpio set 16 ip pd
    raspi-gpio set 20 ip pd
    raspi-gpio set 21 ip pd

    raspi-gpio set 6 ip pd
    raspi-gpio set 13 ip pd
    raspi-gpio set 19 ip pd
    raspi-gpio set 26 ip pd

    MODE_FIELD=$(raspi-gpio get 12 | awk '{ delete vars; for(i = 1; i <= NF; ++i) { n = index($i, "="); if(n) { vars[substr($i, 1, n - 1)] = substr($i, n + 1) } } Var = vars["level"] } { print Var }')
    MODE_PIT=$(raspi-gpio get 16 | awk '{ delete vars; for(i = 1; i <= NF; ++i) { n = index($i, "="); if(n) { vars[substr($i, 1, n - 1)] = substr($i, n + 1) } } Var = vars["level"] } { print Var }')
    MODE_INSPECTIONS=$(raspi-gpio get 20 | awk '{ delete vars; for(i = 1; i <= NF; ++i) { n = index($i, "="); if(n) { vars[substr($i, 1, n - 1)] = substr($i, n + 1) } } Var = vars["level"] } { print Var }')
    MODE_AUDIENCE=$(raspi-gpio get 21 | awk '{ delete vars; for(i = 1; i <= NF; ++i) { n = index($i, "="); if(n) { vars[substr($i, 1, n - 1)] = substr($i, n + 1) } } Var = vars["level"] } { print Var }')

    MODE="$MODE_FIELD$MODE_PIT$MODE_INSPECTIONS$MODE_AUDIENCE"
    #MODE_DEC="$((2#$MODE))"

    FIELD1=$(raspi-gpio get 6 | awk '{ delete vars; for(i = 1; i <= NF; ++i) { n = index($i, "="); if(n) { vars[substr($i, 1, n - 1)] = substr($i, n + 1) } } Var = vars["level"] } { print Var }')
    FIELD2=$(raspi-gpio get 13 | awk '{ delete vars; for(i = 1; i <= NF; ++i) { n = index($i, "="); if(n) { vars[substr($i, 1, n - 1)] = substr($i, n + 1) } } Var = vars["level"] } { print Var }')
    FIELD3=$(raspi-gpio get 19 | awk '{ delete vars; for(i = 1; i <= NF; ++i) { n = index($i, "="); if(n) { vars[substr($i, 1, n - 1)] = substr($i, n + 1) } } Var = vars["level"] } { print Var }')
    FIELD4=$(raspi-gpio get 26 | awk '{ delete vars; for(i = 1; i <= NF; ++i) { n = index($i, "="); if(n) { vars[substr($i, 1, n - 1)] = substr($i, n + 1) } } Var = vars["level"] } { print Var }')
    
    FIELD="$FIELD1$FIELD2$FIELD3$FIELD4"

    if [ $((MODE_FIELD + MODE_PIT + MODE_INSPECTIONS + MODE_AUDIENCE)) -eq 0 ]; then
        report_error_and_exit "ERROR 6: No mode selected! Please verify then reboot."
    fi

    emit "DEBUG FIELD=${FIELD}"
    emit "DEBUG   FIELD1=${FIELD1}"
    emit "DEBUG   FIELD2=${FIELD2}"
    emit "DEBUG   FIELD3=${FIELD3}"
    emit "DEBUG   FIELD4=${FIELD4}"
    emit "DEBUG MODE=${MODE}"
    emit "DEBUG   MODE_FIELD=${MODE_FIELD}"
    emit "DEBUG   MODE_PIT=${MODE_PIT}"
    emit "DEBUG   MODE_INSPECTIONS=${MODE_INSPECTIONS}"
    emit "DEBUG   MODE_AUDIENCE=${MODE_AUDIENCE}"
}

set_kiosk_url() {
    emit ===== set_kiosk_url

    if [ "$MODE" == 0111 ] || [ "$MODE" == 1011 ] || [ "$MODE" == 1101 ] || [ "$MODE" == 1110 ]; then # If mode is inversed we are in dual division mode
        if [ "$FIELD" == 0010 ] ; then #Division 1
            FTCEVENTSERVER_EVENTCODE=$FTCEVENTSERVER_DIVISION1_EVENTCODE
        elif [ "$FIELD" == 0001 ] ; then #Division 2
            FTCEVENTSERVER_EVENTCODE=$FTCEVENTSERVER_DIVISION2_EVENTCODE
        elif [ "$FIELD" == 0011 ] ; then #Division 0
            FTCEVENTSERVER_EVENTCODE=$FTCEVENTSERVER_DIVISION0_EVENTCODE
        elif [ "$FIELD" == 1010 ] ; then #Division 1 Field 1
            FTCEVENTSERVER_EVENTCODE=$FTCEVENTSERVER_DIVISION1_EVENTCODE
            FIELDNUMBER=1
        elif [ "$FIELD" == 0110 ] ; then #Division 1 Field 2
            FTCEVENTSERVER_EVENTCODE=$FTCEVENTSERVER_DIVISION1_EVENTCODE
            FIELDNUMBER=2
        elif [ "$FIELD" == 1001 ] ; then #Division 2 Field 1
            FTCEVENTSERVER_EVENTCODE=$FTCEVENTSERVER_DIVISION2_EVENTCODE
            FIELDNUMBER=1
        elif [ "$FIELD" == 0101 ] ; then #Division 2 Field 2
            FTCEVENTSERVER_EVENTCODE=$FTCEVENTSERVER_DIVISION2_EVENTCODE
            FIELDNUMBER=2
        elif [ "$FIELD" == 1011 ] ; then #Division 0 Field 1 - Interdivisional Finals
            FTCEVENTSERVER_EVENTCODE=$FTCEVENTSERVER_DIVISION0_EVENTCODE
            FIELDNUMBER=1
        elif [ "$FIELD" == 0111 ] ; then #Division 0 Field 2 - Interdivisional Finals
            FTCEVENTSERVER_EVENTCODE=$FTCEVENTSERVER_DIVISION0_EVENTCODE
            FIELDNUMBER=2
        fi
    fi

    common_display_settings="http://${server_addr}/event/${FTCEVENTSERVER_EVENTCODE}/display/"
    common_display_settings="${common_display_settings}?name=${hostname}"
    common_display_settings="${common_display_settings}&scoringBarLocation=bottom"
    common_display_settings="${common_display_settings}&allianceOrientation=standard"
    common_display_settings="${common_display_settings}&liveScores=true"
    common_display_settings="${common_display_settings}&muteRandomizationResults=false"
    common_display_settings="${common_display_settings}&overlay=false"
    common_display_settings="${common_display_settings}&overlayColor=%2300FF00"
    common_display_settings="${common_display_settings}&allianceSelectionStyle=classic"
    common_display_settings="${common_display_settings}&awardsStyle=overlay"
    common_display_settings="${common_display_settings}&previewStyle=overlay"
    common_display_settings="${common_display_settings}&randomStyle=overlay"
    common_display_settings="${common_display_settings}&dualDivisionRankingStyle=sideBySide"
    common_display_settings="${common_display_settings}&rankingsFontSize=larger"
    common_display_settings="${common_display_settings}&showMeetRankings=false"
    common_display_settings="${common_display_settings}&rankingsAllTeams=true"

    if [ "$MODE" == 1000 ] || [ "$MODE" == 0111 ]; then
        if [ "$FIELD" == 1000 ] ; then
            FIELDNUMBER=1
        elif [ "$FIELD" == 0100 ] ; then
            FIELDNUMBER=2
        elif [ "$FIELD" == 0010 ] ; then
            FIELDNUMBER=3
        elif [ "$FIELD" == 0001 ] ; then
            FIELDNUMBER=4
        fi

        if [ -z "$FIELDNUMBER" ] ; then
            report_error_and_exit "ERROR 7: FIELDNUMBER is NOT set!"
        else
            emit "DEBUG FIELDNUMBER is set to ${FIELDNUMBER}."
        fi

        #Get the number of fields for this event
        numFTCEVENTSERVERFIELDS=$(curl -s -L -X GET http://${server_addr}/api/v1/events/${FTCEVENTSERVER_EVENTCODE}/| jq '(.fieldCount)')

        # If the field we have selected is higher than the number of fields we have error out!
        if [ $FIELDNUMBER -gt $numFTCEVENTSERVERFIELDS ] ; then
            report_error_and_exit "ERROR 8: The selected FIELD is incorrect! Please verify then reboot."
        else
            KIOSKURL="${common_display_settings}&type=field&bindToField=${FIELDNUMBER}&mute=true&fieldStyleTimer=true&rankingsShowQR=false"
        fi
    elif [ "$MODE" == 0100 ] || [ "$MODE" == 1011 ]; then # Pit Display
            KIOSKURL="${common_display_settings}&type=pit&bindToField=all&mute=false&fieldStyleTimer&rankingsShowQR=true"
    elif [ "$MODE" == 0010 ] || [ "$MODE" == 1101 ] ; then # Inspection Display
        KIOSKURL="http://${server_addr}/event/${FTCEVENTSERVER_EVENTCODE}/status/proj/3/"
    elif [ "$MODE" == 0001 ] || [ "$MODE" == 1110 ] ; then # Audiance Display
        KIOSKURL="${common_display_settings}&type=audience&bindToField=all&mute=true&fieldStyleTimer=false&rankingsShowQR=false"
    fi
}

#----------------------------------
# Proceed
#----------------------------------

init_logfile
disable_screen_saver
enable_chromium_kiosk
wait_for_active_interface
wait_for_ip_address
check_for_internet
check_for_updatability
locate_scoring_system
find_event_codes

if [ -z "$KIOSKURL" ] ; then
    read_gpio_switches
    set_kiosk_url
fi

#Debugging
emit "DEBUG FTCEVENTSERVER_EVENTCODE=${FTCEVENTSERVER_EVENTCODE}"
emit "DEBUG FTCEVENTSERVER_DIVISION1_EVENTCODE = $FTCEVENTSERVER_DIVISION1_EVENTCODE"
emit "DEBUG FTCEVENTSERVER_DIVISION2_EVENTCODE = $FTCEVENTSERVER_DIVISION2_EVENTCODE"
emit "DEBUG KIOSKURL=${KIOSKURL}"

# Start the Kiosk browser
[ -n "${DISPLAY}" ] && chromium-browser --disable-infobars --kiosk "$KIOSKURL"
